[package]
name = "test-logger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lg"
path = "src/main.rs"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
cmd_lib = "1.3.0"
csv = "1.1.6"
